%% This script copies the smoothed files from the original output folder mri 
% (generated by CAT12 segmentation) in separate folders under a main
% folder.
%--------------------------------------------------------------------------
% Notes: 
% *original smoothed files remain in their present location*
% !!!IMPORTANT!!!Change the directories and the '/' vs '\' depending on mac vs pc.
%--------------------------------------------------------------------------
% Inputs: 
% location is the location of the folder that will contain the smoothed files
location = 'C:\Users\bonilha\Documents\Project_Eleni\Smoothed_Files'; % output
% location1 is the location of the folder that contains the CAT12 output for controls 
location1 = 'C:\Users\bonilha\Documents\Project_Eleni\Controls'
% location2 is the location of the folder that contains the CAT12 output for patients 
location2 = 'C:\Users\bonilha\Documents\Project_Eleni\Patients_preT1'
%--------------------------------------------------------------------------

%% copy controls' smoothed files to separate folder 
% create a folder when you want to save the files
Parentfolder = location;
mkdir(fullfile(Parentfolder,'smooth10_controls_gm'));
mkdir(fullfile(Parentfolder,'smooth10_controls_wm'));

Mainfolder = location1;

f = dir(Mainfolder);

% for grey matter
for i = 1:numel(f)
    if f(i).isdir && ~startsWith(f(i).name,'.')
        GG = dir(fullfile(Mainfolder,f(i).name, 'mri'));
            for j = 1:numel(GG)
                if startsWith(GG(j).name,'smooth10mwp1') 
                    filename1 = append([Mainfolder,'\',f(i).name,'\','mri','\',GG(j).name]);
                    filename2 = append([Parentfolder,'\','smooth10_controls_gm']);
                    copyfile(filename1,filename2);
                    disp(i)
                end
            end
    end
end

%for white matter
for i = 1:numel(f)
    if f(i).isdir && ~startsWith(f(i).name,'.')
        GG = dir(fullfile(Mainfolder,f(i).name, 'mri'));
            for j = 1:numel(GG)
                if startsWith(GG(j).name,'smooth10mwp2') 
                    filename1 = append([Mainfolder,'\',f(i).name,'\','mri','\',GG(j).name]);
                    filename2 = append([Parentfolder,'\','smooth10_controls_wm']);
                    copyfile(filename1,filename2);
                    disp(i)
                end
            end
    end
end

%% copy left patients' smoothed files to separate folder 
% create a folder when you want to save the files
Parentfolder = location;
mkdir(fullfile(Parentfolder,'smooth10_patients_left_gm'));
mkdir(fullfile(Parentfolder,'smooth10_patients_left_wm'));

Mainfolder = location2;

f = dir(Mainfolder);

% for grey matter
for i = 1:numel(f)
    if startsWith(f(i).name,'left')
        G = dir(fullfile(Mainfolder,f(i).name));
        for j = 1:numel(G)
            if G(j).isdir && ~startsWith(G(j).name,'.')
                GG = dir(fullfile(Mainfolder,f(i).name,G(j).name,'mri'));
                for z = 1:numel(GG)
                    if startsWith(GG(z).name,'smooth10mwp1') 
                        filename1 = append([Mainfolder,'\',f(i).name,'\',G(j).name,'\','mri','\',GG(z).name]);
                        filename2 = append([Parentfolder,'\','smooth10_patients_left_gm']);
                        copyfile(filename1,filename2);
                        disp(j)
                    end
                end
            end
        end 
    end
end


%for white matter
for i = 1:numel(f)
    if startsWith(f(i).name,'left')
        G = dir(fullfile(Mainfolder,f(i).name));
        for j = 1:numel(G)
            if G(j).isdir && ~startsWith(G(j).name,'.')
                GG = dir(fullfile(Mainfolder,f(i).name,G(j).name,'mri'));
                for z = 1:numel(GG)
                    if startsWith(GG(z).name,'smooth10mwp2') 
                        filename1 = append([Mainfolder,'\',f(i).name,'\',G(j).name,'\','mri','\',GG(z).name]);
                        filename2 = append([Parentfolder,'\','smooth10_patients_left_wm']);
                        copyfile(filename1,filename2);
                        disp(j)
                    end
                end
            end
        end 
    end
end

%% copy right patients' smoothed files to separate folder 
% create a folder when you want to save the files
Parentfolder = location;
mkdir(fullfile(Parentfolder,'smooth10_patients_right_gm'));
mkdir(fullfile(Parentfolder,'smooth10_patients_right_wm'));

Mainfolder = location2;

f = dir(Mainfolder);

%for grey matter
for i = 1:numel(f)
    if startsWith(f(i).name,'right')
        G = dir(fullfile(Mainfolder,f(i).name));
        for j = 1:numel(G)
            if G(j).isdir && ~startsWith(G(j).name,'.')
                GG = dir(fullfile(Mainfolder,f(i).name,G(j).name,'mri'));
                for z = 1:numel(GG)
                    if startsWith(GG(z).name,'smooth10mwp1') 
                        filename1 = append([Mainfolder,'\',f(i).name,'\',G(j).name,'\','mri','\',GG(z).name]);
                        filename2 = append([Parentfolder,'\','smooth10_patients_right_gm']);
                        copyfile(filename1,filename2);
                        disp(j)
                    end
                end
            end
        end 
    end
end

%for white matter
for i = 1:numel(f)
    if startsWith(f(i).name,'right')
        G = dir(fullfile(Mainfolder,f(i).name));
        for j = 1:numel(G)
            if G(j).isdir && ~startsWith(G(j).name,'.')
                GG = dir(fullfile(Mainfolder,f(i).name,G(j).name,'mri'));
                for z = 1:numel(GG)
                    if startsWith(GG(z).name,'smooth10mwp2') 
                        filename1 = append([Mainfolder,'\',f(i).name,'\',G(j).name,'\','mri','\',GG(z).name]);
                        filename2 = append([Parentfolder,'\','smooth10_patients_right_wm']);
                        copyfile(filename1,filename2);
                        disp(j)
                    end
                end
            end
        end 
    end
end